import type { GitHubAppClient } from "@sayan-sentinel/github";

export class PatchNotApprovedError extends Error {
  constructor() {
    super(
      "Cannot open a pull request for a patch that has not been explicitly approved by a human.",
    );
    this.name = "PatchNotApprovedError";
  }
}

export interface ApprovedPatch {
  patchId: string;
  filePath: string;
  updatedFileContent: string;
  /** The blob sha of the file being replaced — required by GitHub's Contents API for optimistic-concurrency updates. */
  currentFileSha: string;
  commitMessage: string;
  explanation: string;
  risks?: string;
  limitations?: string;
  /**
   * Required — the identity of the human who approved this patch.
   * `applyApprovedPatchAsPullRequest` refuses to run without it
   * (Section 27: "Never automatically merge," and more fundamentally,
   * never push at all without a human in the loop first).
   */
  approvedByUserId: string;
  installationId: number;
  repositoryOwner: string;
  repositoryName: string;
  baseBranch: string;
  headSha: string;
}

export interface ApplyPatchDependencies {
  githubClient: Pick<GitHubAppClient, "createBranch" | "commitFileChange" | "createPullRequest">;
}

function buildPullRequestBody(patch: ApprovedPatch): string {
  const sections = [
    "This pull request was generated by Sayan Sentinel and approved by a human reviewer before being opened.",
    "",
    "## Explanation",
    patch.explanation,
  ];
  if (patch.risks) sections.push("", "## Risks to double-check", patch.risks);
  if (patch.limitations) sections.push("", "## Limitations", patch.limitations);
  sections.push("", "---", `Approved by: ${patch.approvedByUserId}`);
  return sections.join("\n");
}

/**
 * The only path in this codebase that writes a remediation to GitHub.
 * Throws `PatchNotApprovedError` — refusing to run at all — unless
 * `approvedByUserId` is set. This function does not decide whether a
 * patch *should* be approved; that decision happens upstream (a human,
 * via the product's approval UI, not built yet) and is passed in already
 * made.
 */
export async function applyApprovedPatchAsPullRequest(
  patch: ApprovedPatch,
  deps: ApplyPatchDependencies,
): ReturnType<ApplyPatchDependencies["githubClient"]["createPullRequest"]> {
  if (!patch.approvedByUserId) {
    throw new PatchNotApprovedError();
  }

  const branchName = `sentinel/fix-${patch.patchId}`;

  await deps.githubClient.createBranch(
    patch.installationId,
    patch.repositoryOwner,
    patch.repositoryName,
    branchName,
    patch.headSha,
  );

  await deps.githubClient.commitFileChange(
    patch.installationId,
    patch.repositoryOwner,
    patch.repositoryName,
    {
      branch: branchName,
      path: patch.filePath,
      content: patch.updatedFileContent,
      message: patch.commitMessage,
      sha: patch.currentFileSha,
    },
  );

  return deps.githubClient.createPullRequest(
    patch.installationId,
    patch.repositoryOwner,
    patch.repositoryName,
    {
      title: `Sentinel: ${patch.commitMessage}`,
      head: branchName,
      base: patch.baseBranch,
      body: buildPullRequestBody(patch),
    },
  );
}
