export interface DiscoveredForm {
  action?: string;
  method: string;
  fieldNames: string[];
}

/**
 * These extractors are deliberately regex-based rather than a full HTML
 * parser — this package has no HTML/DOM dependency, matching the
 * project's preference for dependency-free, fully-auditable security-
 * critical primitives (see `ip-blocklist.ts`'s equivalent choice). This is
 * a **known, documented limitation**: severely malformed HTML, HTML
 * generated by JavaScript at runtime (a client-side-rendered SPA's routes
 * are invisible to a plain HTML fetch), or deliberately obfuscated markup
 * can under-discover. This is acceptable for a conservative discovery
 * pass — under-discovering is a availability/completeness limitation, not
 * a safety one, since every URL found here is still routed through
 * `SafeHttpClient`/Scope Guard before ever being requested.
 */

const HREF_PATTERN = /\bhref\s*=\s*["']([^"']+)["']/gi;
const SCRIPT_SRC_PATTERN = /<script\b[^>]*\bsrc\s*=\s*["']([^"']+)["']/gi;
const FORM_BLOCK_PATTERN = /<form\b([^>]*)>([\s\S]*?)<\/form>/gi;
const ATTRIBUTE_PATTERN = /(\w[\w-]*)\s*=\s*["']([^"']*)["']/g;
const FIELD_NAME_PATTERN = /<(?:input|select|textarea)\b[^>]*\bname\s*=\s*["']([^"']+)["']/gi;

/** Extracts every `href="..."` value from `<a>`/`<link>` tags (and anything else carrying an href attribute — harmless over-extraction for a discovery pass). */
export function extractLinks(html: string): string[] {
  return matchAll(html, HREF_PATTERN);
}

export function extractScriptSrcs(html: string): string[] {
  return matchAll(html, SCRIPT_SRC_PATTERN);
}

/**
 * Extracts `<form>` blocks: action URL (if any — an omitted action submits
 * to the current page, which callers should resolve against the page URL
 * themselves), method (defaults to GET per the HTML spec when omitted),
 * and every named input/select/textarea field. Never auto-submits
 * anything — this only reads static markup.
 */
export function extractForms(html: string): DiscoveredForm[] {
  const forms: DiscoveredForm[] = [];
  let match: RegExpExecArray | null;
  FORM_BLOCK_PATTERN.lastIndex = 0;

  while ((match = FORM_BLOCK_PATTERN.exec(html))) {
    const [, attributesText, bodyText] = match;
    const attributes = parseAttributes(attributesText ?? "");
    const fieldNames = matchAll(bodyText ?? "", FIELD_NAME_PATTERN);

    forms.push({
      action: attributes.action,
      method: (attributes.method ?? "GET").toUpperCase(),
      fieldNames: [...new Set(fieldNames)],
    });
  }

  return forms;
}

function parseAttributes(attributesText: string): Record<string, string> {
  const result: Record<string, string> = {};
  let match: RegExpExecArray | null;
  ATTRIBUTE_PATTERN.lastIndex = 0;
  while ((match = ATTRIBUTE_PATTERN.exec(attributesText))) {
    const [, name, value] = match;
    if (name) result[name.toLowerCase()] = value ?? "";
  }
  return result;
}

function matchAll(text: string, pattern: RegExp): string[] {
  const results: string[] = [];
  let match: RegExpExecArray | null;
  pattern.lastIndex = 0;
  while ((match = pattern.exec(text))) {
    if (match[1]) results.push(match[1]);
  }
  return results;
}
